### ISSUE TITLE
Feature request: Disable update check

### ISSUE THREAD

**Issue by SlimeDog** [SamJakob/MassiveStats#1]
Using Songoda's TreeAssist. It makes a call-out to massivestats.com. According to Brianna, it's an update check. She suggested that I ask you to...

Please provide a configuration option to disable update checks to MassiveStats.com.

I am not sure why that would be called from the API rather than the individual plugins, but perhaps it is also called by Arconix. I'm asking anyway.

**Comment by SamJakob** [comment]
This is essentially already a feature.  
  
The plugin developer, Brianna, needs to disable it in her plugin by either not instantiating Massive or calling `massive.stop();` in her code if the user decides that they want to disable this feature.  
  
I could add a global option as she suggests but then other developers would say they want explicit control and it could break plugins that use an older version of Massive, anyway.
